from pathlib import Path
p=Path('/tmp/mem/www/js/data.js')
s=p.read_text()
s=s.replace('const MAX_DESIGNED_WAVE = 50;', '''const MAX_DESIGNED_WAVE = 80;\n\n// V5.2 MAP ARCHITECTURE — hărți multiple, fiecare cu traseu și poziții de noduri proprii.\nconst MAPS = {\n  neuralCore: { id:'neuralCore', name:'🧠 Nucleul Neural', path:[\n    {x:40,y:-20},{x:40,y:100},{x:300,y:100},{x:300,y:220},{x:60,y:220},{x:60,y:340},{x:320,y:340},{x:320,y:460},{x:150,y:460},{x:150,y:590}\n  ], slots:[\n    {x:100,y:60},{x:250,y:55},{x:335,y:160},{x:150,y:160},{x:150,y:255},{x:20,y:280},{x:100,y:375},{x:210,y:285},{x:340,y:400},{x:250,y:425},{x:60,y:425},{x:110,y:525},{x:210,y:525}\n  ]},\n  vascularLabyrinth: { id:'vascularLabyrinth', name:'🩸 Labirint Vascular', path:[\n    {x:-20,y:70},{x:100,y:70},{x:100,y:180},{x:300,y:180},{x:300,y:70},{x:380,y:70},{x:380,y:300},{x:220,y:300},{x:220,y:430},{x:60,y:430},{x:60,y:570},{x:180,y:570},{x:180,y:650}\n  ], slots:[\n    {x:45,y:125},{x:155,y:125},{x:255,y:125},{x:335,y:125},{x:65,y:250},{x:145,y:245},{x:255,y:245},{x:335,y:245},{x:120,y:360},{x:285,y:360},{x:25,y:500},{x:120,y:510},{x:245,y:520},{x:300,y:600}\n  ]},\n  synapseGarden: { id:'synapseGarden', name:'🌿 Grădina Sinaptică', path:[\n    {x:180,y:-20},{x:180,y:90},{x:80,y:150},{x:80,y:270},{x:280,y:270},{x:280,y:150},{x:180,y:90},{x:180,y:380},{x:60,y:460},{x:60,y:570},{x:180,y:610}\n  ], slots:[\n    {x:120,y:55},{x:240,y:55},{x:35,y:190},{x:125,y:190},{x:235,y:190},{x:325,y:190},{x:35,y:330},{x:125,y:330},{x:235,y:330},{x:325,y:330},{x:120,y:445},{x:240,y:445},{x:20,y:520},{x:300,y:520}\n  ]},\n  quantumMembrane: { id:'quantumMembrane', name:'⚛️ Membrana Cuantică', path:[\n    {x:-20,y:110},{x:90,y:110},{x:180,y:35},{x:270,y:110},{x:380,y:110},{x:300,y:230},{x:300,y:360},{x:180,y:360},{x:60,y:360},{x:60,y:500},{x:180,y:500},{x:180,y:660}\n  ], slots:[\n    {x:45,y:55},{x:125,y:90},{x:235,y:90},{x:335,y:55},{x:125,y:210},{x:235,y:210},{x:335,y:210},{x:20,y:300},{x:110,y:315},{x:250,y:315},{x:340,y:315},{x:120,y:430},{x:240,y:430},{x:70,y:555},{x:290,y:555}\n  ]}\n};\nconst MAP_ORDER = Object.keys(MAPS);''')
# Add shooter flags to selected enemies
s=s.replace("phase: true },", "phase: true, shooter: true, shootRate: 2.8, shootRange: 145, shotDamage: 7 },")
s=s.replace("adaptive: true }", "adaptive: true, shooter: true, shootRate: 2.1, shootRange: 175, shotDamage: 11 }")
s=s.replace("boss: true }", "boss: true, shooter: true, shootRate: 1.35, shootRange: 220, shotDamage: 18 }")
# add new ranged enemy
s=s.replace("  adaptive: { id: 'adaptive', name: 'Patogen Adaptiv', icon: '🧠', hp: 95, speed: 58, damage: 9, reward: 21, color: '#f97316', adaptive: true, shooter: true, shootRate: 2.1, shootRange: 175, shotDamage: 11 }", "  adaptive: { id: 'adaptive', name: 'Patogen Adaptiv', icon: '🧠', hp: 95, speed: 58, damage: 9, reward: 21, color: '#f97316', adaptive: true, shooter: true, shootRate: 2.1, shootRange: 175, shotDamage: 11 },\n  artillery: { id:'artillery', name:'Spora Artilerie', icon:'🧿', hp:72, speed:34, damage:10, reward:24, color:'#fb923c', shooter:true, shootRate:2.4, shootRange:190, shotDamage:15 },")
# boss and artillery in waves, extend patterns
s=s.replace("if (n >= 22) groups.push({ type: 'adaptive', count: 1 + Math.floor(n / 12), hpMult: diff * 1.08, interval: 0.95 });", """if (n >= 22) groups.push({ type: 'adaptive', count: 1 + Math.floor(n / 12), hpMult: diff * 1.08, interval: 0.95 });\n    if (n >= 28) groups.push({ type: 'artillery', count: 1 + Math.floor(n / 14), hpMult: diff * 1.12, interval: 1.35 });\n    if (n >= 35) groups.push({ type: 'adaptive', count: 2 + Math.floor(n / 10), hpMult: diff * 1.16, interval: 0.72 });\n    if (n >= 50) groups.push({ type: 'artillery', count: 2 + Math.floor(n / 12), hpMult: diff * 1.2, interval: 1.0 });""")
# boss escorts more
s=s.replace("if (n >= 10) groups.push({ type: 'fast', count: 3 + Math.floor(n / 6), hpMult: diff * 0.7, interval: 0.35 });", "if (n >= 10) groups.push({ type: 'fast', count: 3 + Math.floor(n / 6), hpMult: diff * 0.7, interval: 0.35 });\n    if (n >= 25) groups.push({ type: 'adaptive', count: 2 + Math.floor(n / 8), hpMult: diff, interval: 0.65 });\n    if (n >= 40) groups.push({ type: 'artillery', count: 1 + Math.floor(n / 15), hpMult: diff * 1.15, interval: 1.1 });")
p.write_text(s)

p=Path('/tmp/mem/www/js/game.js')
s=p.read_text()
# replace hardcoded path block
start=s.index('  const PATH = [')
end=s.index('  // precompute segment lengths + total length', start)
s=s[:start]+'''  // V5.2: harta activă — rendererul și gameplay-ul folosesc aceeași geometrie.\n  let activeMapId = (typeof SAVE !== 'undefined' && SAVE.selectedMap) || 'neuralCore';\n  let ACTIVE_MAP = MAPS[activeMapId] || MAPS.neuralCore;\n  let PATH = ACTIVE_MAP.path.map(p => ({...p}));\n  let SLOT_POS = ACTIVE_MAP.slots.map(p => ({...p}));\n  let CORE_POS = {...PATH[PATH.length - 1]};\n\n'''+s[end:]
# seg lens recalculation helper
old="""  // precompute segment lengths + total length\n  let segLens = [], totalLen = 0;\n  for (let i = 0; i < PATH.length - 1; i++) {\n    const dx = PATH[i + 1].x - PATH[i].x, dy = PATH[i + 1].y - PATH[i].y;\n    const len = Math.hypot(dx, dy);\n    segLens.push(len);\n    totalLen += len;\n  }"""
new="""  // precompute segment lengths + total length\n  let segLens = [], totalLen = 0;\n  function rebuildPathMetrics(){\n    segLens=[]; totalLen=0;\n    for(let i=0;i<PATH.length-1;i++){ const dx=PATH[i+1].x-PATH[i].x,dy=PATH[i+1].y-PATH[i].y,len=Math.hypot(dx,dy); segLens.push(len); totalLen+=len; }\n    CORE_POS={...PATH[PATH.length-1]};\n  }\n  rebuildPathMetrics();\n  function setMap(mapId){\n    const m=MAPS[mapId]||MAPS.neuralCore; activeMapId=m.id; ACTIVE_MAP=m; PATH=m.path.map(p=>({...p})); SLOT_POS=m.slots.map(p=>({...p})); rebuildPathMetrics();\n  }"""
s=s.replace(old,new)
# fresh run add map, enemyProjectiles, story
s=s.replace("waveNumber: 1,", "waveNumber: 1,\n      mapId: activeMapId,\n      mapName: ACTIVE_MAP.name,\n      narrativeStage: 1,")
s=s.replace("enemies: [],\n      projectiles: [],", "enemies: [],\n      projectiles: [], enemyProjectiles: [],")
# startWave narrative callback
s=s.replace("AudioSys.waveStart();", "AudioSys.waveStart();\n    if (Main.showNarrativeBeat) Main.showNarrativeBeat(R.waveNumber, R.mapId);")
# spawn enemy shooter fields
s=s.replace("phaseTimer: def.phase ? 1.5 : 0, phased: false, healTimer: 0, dotTimer: 0, infectedTimer: 0, adaptiveArmor: 0,", "phaseTimer: def.phase ? 1.5 : 0, phased: false, healTimer: 0, dotTimer: 0, infectedTimer: 0, adaptiveArmor: 0, shootTimer: def.shooter ? (0.8 + Math.random()*def.shootRate) : 9999,")
# insert enemy shooting before enemy move distance
needle="""      const genomeSpeed = e.genome && e.genome.speed ? (1 + e.genome.speed) : 1;\n      e.distance += def.speed * e.slowFactor * genomeSpeed * dt;"""
repl="""      // Unele amenințări sunt atacatori la distanță; nu toate trag.\n      if(def.shooter && !e.phased){\n        e.shootTimer -= dt;\n        const ep=posAtDistance(e.distance);\n        if(e.shootTimer<=0 && e.distance < totalLen-45){\n          const dCore=Math.hypot(CORE_POS.x-ep.x,CORE_POS.y-ep.y);\n          if(dCore <= (def.shootRange||160)) {\n            R.enemyProjectiles.push({x:ep.x,y:ep.y,target:'core',speed:155+(def.boss?35:0),damage:def.shotDamage||8,color:def.color,life:4.5});\n            spawnParticles(ep.x,ep.y,def.color,5,20);\n          }\n          e.shootTimer=def.shootRate||2.5;\n        }\n      }\n      const genomeSpeed = e.genome && e.genome.speed ? (1 + e.genome.speed) : 1;\n      e.distance += def.speed * e.slowFactor * genomeSpeed * dt;"""
s=s.replace(needle,repl)
# insert enemy projectile update before shockwaves
needle="""    // shockwaves / visual effects\n"""
repl="""    // enemy projectiles — focuri rare, lizibile, care lovesc Nucleul.\n    for(let i=R.enemyProjectiles.length-1;i>=0;i--){\n      const p=R.enemyProjectiles[i]; const dx=CORE_POS.x-p.x,dy=CORE_POS.y-p.y,dist=Math.hypot(dx,dy);\n      if(dist<=p.speed*dt){\n        R.coreHP=Math.max(0,R.coreHP-p.damage); R.shockwaves.push({x:CORE_POS.x,y:CORE_POS.y,r:4,max:38,life:.35,color:p.color}); spawnParticles(CORE_POS.x,CORE_POS.y,p.color,9,35); R.cameraShake=Math.max(R.cameraShake,.1); R.enemyProjectiles.splice(i,1);\n        if(R.coreHP<=0){ R.coreHP=0; endRun('gameover'); return; }\n      } else { p.x+=(dx/dist)*p.speed*dt; p.y+=(dy/dist)*p.speed*dt; p.life-=dt; if(p.life<=0)R.enemyProjectiles.splice(i,1); }\n    }\n\n    // shockwaves / visual effects\n"""
s=s.replace(needle,repl)
# render enemy projectiles
s=s.replace("R.projectiles.forEach(drawProjectileReborn);", "R.projectiles.forEach(drawProjectileReborn);\n    (R.enemyProjectiles||[]).forEach(drawEnemyProjectile);")
# add draw function
s=s.replace("function drawBeam(b){", "function drawEnemyProjectile(p){const q=w2s(p.x,p.y),r=3.8*scale;ctx.save();ctx.shadowColor=p.color;ctx.shadowBlur=18*scale;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(q.x,q.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=.8*scale;ctx.beginPath();ctx.arc(q.x,q.y,r*1.8,0,Math.PI*2);ctx.stroke();ctx.restore();}\n  function drawBeam(b){")
# snapshot/restore before init
insert="""\n  function getSnapshot(){\n    if(!R) return null;\n    return {\n      energy:R.energy,coreHP:R.coreHP,coreMaxHP:R.coreMaxHP,waveNumber:R.waveNumber,mapId:R.mapId||activeMapId,\n      waveInProgress:R.waveInProgress,spawnGroups:R.spawnGroups.map(g=>({...g})),\n      enemies:R.enemies.map(e=>({...e})),projectiles:R.projectiles.map(p=>({x:p.x,y:p.y,targetId:p.target?p.target.id:null,speed:p.speed,damage:p.damage,color:p.color,slow:p.slow,chain:p.chain,infect:p.infect,temporal:p.temporal})),\n      enemyProjectiles:(R.enemyProjectiles||[]).map(p=>({...p})),particles:R.particles.map(p=>({...p})),anomalies:R.anomalies.map(a=>({...a})),shockwaves:R.shockwaves.map(a=>({...a})),beams:R.beams.map(a=>({...a})),\n      nodes:R.nodes.map(n=>({slot:n.slot,typeId:n.typeId,level:n.level,cooldown:n.cooldown})),selected:R.selected,speedMult:R.speedMult,\n      killsThisRun:R.killsThisRun,bossKillsThisRun:R.bossKillsThisRun,nodeTypeCountsThisRun:R.nodeTypeCountsThisRun,maxEmpInRun:R.maxEmpInRun,maxEnergyInRun:R.maxEnergyInRun,perfectWaveAchieved:R.perfectWaveAchieved,allNodeTypesUsed:R.allNodeTypesUsed,coreHPAtWaveStart:R.coreHPAtWaveStart,runCrystalsEarned:R.runCrystalsEarned,nextEnemyId:R.nextEnemyId,\n      finalized:false,overdrive:R.overdrive,overdriveActive:R.overdriveActive,combo:R.combo,comboTimer:R.comboTimer,battleDirector:R.battleDirector,fusionCount:R.fusionCount,currentWaveMeta:R.currentWaveMeta,visualTime:R.visualTime\n    };\n  }\n  function restoreTargets(){ if(!R)return; const byId=new Map(R.enemies.map(e=>[e.id,e])); R.projectiles.forEach(p=>p.target=byId.get(p.targetId)||null); R.projectiles=R.projectiles.filter(p=>p.target); }\n"""
s=s.replace("  function init(canvasEl) {", insert+"\n  function init(canvasEl) {")
# startNewRun map and restore
old="""  function startNewRun(preset) {\n    R = preset || freshRun(SAVE);\n    resize();"""
new="""  function startNewRun(preset) {\n    if(preset && preset.mapId) setMap(preset.mapId); else setMap((preset&&preset.mapId)||activeMapId);\n    R = preset || freshRun(SAVE);\n    R.mapId=activeMapId; R.mapName=ACTIVE_MAP.name;\n    restoreTargets();\n    resize();"""
s=s.replace(old,new)
# exports
s=s.replace("VW, VH, PATH, SLOT_POS, CORE_POS,", "VW, VH, get PATH(){return PATH;}, get SLOT_POS(){return SLOT_POS;}, get CORE_POS(){return CORE_POS;}, setMap, get mapId(){return activeMapId;}, get mapName(){return ACTIVE_MAP.name;},")
s=s.replace("activateOverdrive,", "activateOverdrive, getSnapshot,")
p.write_text(s)
